services:
  php:
    image: fat-nerd-php:0.1
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
#      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/custom.conf
      - ./src:/var/www/html
    ports:
      - "5173:5173"
  nginx:
    image: nginx:stable-alpine
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
  db:
    image: mariadb:10.5
    ports:
      - "3366:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: fat_nerd
    volumes:
      - .data/db:/var/lib/mysql
#  redis:
#    image: redis:alpine